import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * Responds when the user clicks on the on-screen map, and selects/ deselects the territory they are clicking on
 */
public class BoardMouseListener extends MouseAdapter {

    /**
     * The BoardView the BoardMouseListener is listening to
     */
    private BoardView boardView;

    /**
     * Constructor for BoardMouseListener
     * @param boardView The BoardView the BoardMouseListener is listening to
     */
    public BoardMouseListener(BoardView boardView){
        this.boardView = boardView;
    }

    /**
     * Selects/deselects the correct territory when the user clicks the map
     * @param me A MouseEvent generated by the BoardPanel when the user clicks on it
     */
    @Override
    public void mouseClicked(MouseEvent me) {
        super.mouseClicked(me);

        Board board = boardView.getBoardController().getBoard();

        if(board == null) return;

        for(Territory t: board.getTerritoryList()) {
            if (t.getPolygon().contains(me.getPoint())) {
                board.toggleTerritorySelection(t);
                boardView.getMapPanel().drawTerritory(t, boardView.getMapPanel().getGraphics());
            }
        }
    }
}
